name: trinity

services:
  trinity:
    build:
      context: .
      dockerfile: Dockerfile.trinity
    image: chiyoi/trinity
    container_name: trinity
    hostname: trinity
    # restart: always
    networks:
      - trinity_network
      - neko03_network
    ports:
      - 3333:80

  aira:
    build:
      context: .
      dockerfile: Dockerfile.aira
    image: chiyoi/trinity-aira
    container_name: aira
    hostname: aira
    # restart: always
    networks:
      - trinity_network

  # maru:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.maru
  #   image: chiyoi/trinity-maru
  #   container_name: maru
  #   hostname: maru
  #   # restart: always
  #   networks:
  #     - trinity_network
  #   depends_on:
  #     - gocq

  # gocq:
  #   build: ./third_party/gocq
  #   image: chiyoi/gocq
  #   container_name: gocq
  #   hostname: gocq
  #   # restart: always
  #   networks:
  #     - trinity_network
  #   volumes:
  #     - gocq-neko0001:/gocq

networks:
  trinity_network:
    name: trinity_network
  neko03_network:
    name: neko03_network
    external: true

# volumes:
#   gocq-neko0001:
#     name: gocq-neko0001
#     external: true