FROM golang:1.19

WORKDIR /build
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./config.go ./
COPY ./internal ./internal
COPY ./cmd ./cmd
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 go build -o ./maru ./cmd/maru

FROM alpine:3.16

COPY --from=0 /build/maru /bin/maru

EXPOSE 80
EXPOSE 8080

WORKDIR /maru
CMD ["maru"]
