name: trinity

services:
  trinity:
    build:
      context: .
      dockerfile: Dockerfile.trinity
    image: chiyoi/trinity
    container_name: trinity
    hostname: trinity
    networks:
      - trinity_network
      - neko03_network
    restart: unless-stopped

  aira:
    build:
      context: .
      dockerfile: Dockerfile.aira
    image: chiyoi/trinity-aira
    container_name: aira
    hostname: aira
    networks:
      - trinity_network
    restart: unless-stopped

  maru:
    build:
      context: .
      dockerfile: Dockerfile.maru
    image: chiyoi/trinity-maru
    container_name: maru
    hostname: maru
    networks:
      - trinity_network
    restart: unless-stopped
    depends_on:
      - gocq

  gocq:
    build:
      context: .
      dockerfile: Dockerfile.gocq
    image: chiyoi/gocq
    container_name: gocq
    hostname: gocq
    networks:
      - trinity_network
    volumes:
      - gocq-neko0001:/gocq/neko0001
    restart: unless-stopped

networks:
  trinity_network:
    name: trinity_network
  neko03_network:
    name: neko03_network
    external: true

volumes:
  gocq-neko0001:
    name: gocq-neko0001
    external: true
