name: trinity

services:
  trinity:
    build:
      context: .
      dockerfile: Dockerfile.trinity
    image: chiyoi/trinity
    container_name: trinity
    hostname: trinity
    # restart: always
    networks:
      - trinity_network
      - neko03_network
    ports:
      - 3333:80

  aira:
    build:
      context: .
      dockerfile: Dockerfile.aira
    image: chiyoi/trinity-aira
    container_name: aira
    hostname: aira
    # restart: always
    networks:
      - trinity_network

networks:
  trinity_network:
    name: trinity_network
  neko03_network:
    name: neko03_network
    external: true
