FROM alpine:3.17

RUN apk add --no-cache ffmpeg

COPY ./third_party/gocq/config.yml /gocq/config.yml
COPY ./third_party/gocq/go-cqhttp /bin/go-cqhttp

EXPOSE 80

WORKDIR /gocq
CMD ["go-cqhttp", "-faststart"]